services:
  test-db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env.test
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  test-redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: [ "redis-server", "--requirepass", "password" ]
